### PR TITLE
Add gem source. DRY Gemfile and gemspec. Stop tracking Gemfile.lock

### PR DESCRIPTION
**Pull request by kirkland**
Changes mainly inspired by this: http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

### CODE REVIEW

**Comment by nmertaugh** [comment]
Yup. looks awesome @kirkland. For publishing this, do you think we should bump the version number? Should we always bump every time we publish the gem again?

**Comment by kirkland** [comment]
I guess so? Does Rubygems let you re-publish a gem with the same version and different code? Seems like they shouldn't allow it, otherwise seems like we shouldn't do it anyway.

**Comment by nmertaugh** [comment]
@kirkland you can `yank` a gem version from rubygems, then re-publish it. But yeah, seems bad. So maybe bump the minor version number on this and then ship it?

**Comment by nmertaugh** [comment]
Hey @kirkland - was this merged, or closed intentionally without merging?

**Comment by kirkland** [comment]
I thought I merged it! I did not try to publish to Ruby gems though.

**Pull request closed without merging**
